apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.cronjob.name }}
  namespace: {{ .Values.namespace }}
spec:
  schedule: "{{ .Values.cronjob.schedule }}"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
          - name: init
            image: {{ .Values.deployment.image }}
            ports:
            - containerPort: {{ .Values.deployment.port }}
            envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
            securityContext:
              runAsUser: 1000
              runAsGroup: 33
            command:
            - sh
            - -c
            - |
              until /opt/znuny/bin/otrs.Console.pl Maint::Database::Check; do
                echo "Database maintenance check failed, retrying..."
                sleep 5
              done

              echo "exiting..."
              sleep 20
          containers:
          - name: {{ .Values.deployment.name }}
            image: {{ .Values.deployment.image }}
            ports:
            - containerPort: {{ .Values.deployment.port }}
            envFrom:
            - secretRef:
                name: {{ .Values.secret.name }}
            securityContext:
              runAsUser: 1000
              runAsGroup: 33
            command:
            - sh
            - -c
            - |
                /opt/znuny/bin/znuny.Daemon.pl start
                sleep 1d
          restartPolicy: Never
