apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}
  namespace: znuny
spec:
  replicas: {{ .Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - control-plane
      tolerations:
      - effect: NoSchedule
        key: controlplane
        operator: Equal
        value: "true"
      volumes:
      - name: znuny-articles
        persistentVolumeClaim:
          claimName: {{ .Values.persistentVolumeClaim.app.name }}
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
        env:
        - name: MARIADB_HOST
          value: {{ .Values.environment.MARIADB_HOST}}
        - name: MARIADB_DATABASE
          value: {{ .Values.environment.MARIADB_DATABASE }}
        - name: MARIADB_USER
          value: {{ .Values.environment.MARIADB_USER }}
        - name: MARIADB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.secret.name }}
              key: password
        volumeMounts:
        - name: znuny-articles
          mountPath: /opt/znuny/var/articles
