apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.app.name }}
spec:
  storageClassName: nginx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.persistentVolumeClaim.db.name }}
spec:
  storageClassName: nginx
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi