apiVersion: v1
stringData:
    MARIADB_DATABASE: {{ .Values.secret.stringData.MARIADB_DATABASE }}
    MARIADB_USER: {{ .Values.secret.stringData.MARIADB_USER }}
    MARIADB_HOST: "{{ .Values.secret.stringData.MARIADB_HOST }}.{{ .Values.namespace }}.svc.cluster.local"
    MARIADB_PASSWORD: "{{ .Values.secret.stringData.MARIADB_PASSWORD }}"
    MARIADB_ROOT_PASSWORD: "{{ .Values.secret.stringData.MARIADB_PASSWORD }}"
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  namespace: {{ .Values.namespace }}