environment:
  MARIADB_DATABASE: znuny
  MARIADB_USER: znuny

deployment:
  name: znuny-app
  replicas: 1
  image: znuny:7
  port: 80

statefulset:
  name: znuny-db
  replicas: 1
  image: mariadb:10.6
  port: 3306

secret:
  name: znuny-db-secret

service:
  db:
    name: znuny-db-svc
    port: 3306

  app:
    name: znuny-app-svc
    port: 80

persistentVolumeClaim:
  app:
    name: znuny-articles
    
  db:
    name: mariadb-storage

ingress:
  enable: true
  name: znuny-ingress
  host: znuny.local
  ingressClass: nginx